name: Build Shims (GoodSilver)

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write

    strategy: 
      matrix:
        board: [nissa, dedede, corsola, asurada, atlas, cherry, drallion, geralt, nocturne, rammus, rex, sarien, skyrim, staryu]

    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10240
          swap-size-mb: 64
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: download repo
        uses: actions/checkout@v4
      
      - name: run build
        run: |
          set -x
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install -y pv aria2

          sudo QUIET=1 ./build_complete.sh "${{ matrix.board }}" || sudo QUIET=1 ./build_complete.sh "${{ matrix.board }}" || sudo rm data/goodsilver_${{ matrix.board }}.bin

      - name: upload disk image
        uses: actions/upload-artifact@v4
        with:
          name: goodsilver_${{ matrix.board }}
          path: data/goodsilver_*.bin
          compression-level: 7

      - name: compress disk image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -x
          for image in "data/goodsilver_${{ matrix.board }}"*.bin; do
            zip_file="${image%.bin}.zip"
            sudo zip -9 "$zip_file" "$image"
          done
      
      - name: create release
        uses: ading2210/gh-large-releases@main
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: data/goodsilver_*.zip


