on: [push]

jobs:
  build:
    strategy: 
      matrix:
        board: [nissa, dedede, corsola, asurada, atlas, cherry, drallion, geralt, nocturne, rammus, rex, sarien, skyrim, staryu, eve]

    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 32768
          swap-size-mb: 64
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: download repo
        uses: actions/checkout@v4

      - name: run build
        run: |
          sudo apt autoremove --purge -y
          sudo apt clean
          df -h /
          set -x
          sudo apt update
          sudo apt install -y pv
          sudo QUIET=1 ./build_complete.sh "${{ matrix.board }}" || sudo QUIET=1 ./build_complete.sh "${{ matrix.board }}" || sudo rm data/quickrecovery_${{ matrix.board }}.bin
      - name: upload img
        uses: actions/upload-artifact@v4
        with:
          name: quickrecovery_${{ matrix.board }}
          path: data/quickrecovery_*.bin
          compression-level: 7